/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "social"
include(":social-api")
include(":social-api-bukkit")
include(":social-bukkit")
include(":social-common")
include(":social-paper")
project(":social-api").projectDir = file("api")
project(":social-api-bukkit").projectDir = file("api-bukkit")
project(":social-bukkit").projectDir = file("platform-bukkit")
project(":social-common").projectDir = file("platform-common")
project(":social-paper").projectDir = file("platform-paper")
