/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("com.gradleup.shadow") version "9.0.0-beta10"
}

dependencies {
    api(project(":social-api-bukkit"))
    api(project(path = ":social-common", configuration = "shadow"))
    api(libs.org.bstats.bstats.bukkit)
    compileOnly(libs.org.incendo.cloud.paper)
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.net.kyori.adventure.platform.bukkit)
    compileOnly(libs.me.clip.placeholderapi)
    compileOnly(libs.com.discordsrv.discordsrv)
}

tasks.shadowJar {
    relocate("org.bstats", "ovh.mythmc.social.libs.org.bstats")
}

description = "social-bukkit"
