/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(path = ":social-api-bukkit"))
    api(project(path = ":social-common"))
    api(libs.org.bstats.bstats.bukkit)
    api(libs.com.github.imdanix.minitranslator) // Used for PlaceholderAPI legacy codes
    compileOnly(libs.org.incendo.cloud.paper)
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.net.kyori.adventure.platform.bukkit)
    compileOnly(libs.me.clip.placeholderapi)
    compileOnly(libs.com.discordsrv.discordsrv)
}

tasks {
    processResources {
        val replacements = mapOf(
            "version" to version.toString()
        )
        inputs.properties(replacements)
        filesMatching("plugin.yml") {
            expand(replacements)
        }
    }
}

description = "social-bukkit"
