name: social
authors: [myth-MC, U8092]
version: '${project.version}'
api-version: 1.20

main: ovh.mythmc.social.bukkit.SocialBukkitPlugin
softdepend: [ PlaceholderAPI ]

commands:
  social:
    permission: social.admin
  pm:
    permission: social.user
    aliases:
      - message
      - msg
      - whisper
      - w

permissions:
  social.user:
    default: true
  social.admin:
    default: op
    children:
      - social.command.*
  social.command.*:
    default: op
    children:
      - social.command.channel
      - social.command.nickname
      - social.command.reload
      - social.command.socialspy
  social.command.channel:
    default: false
  social.command.nickname:
    default: false
  social.command.reload:
    default: false
  social.command.socialspy:
    default: false