name: social
authors: [myth-MC, U8092]
version: '${project.version}'
api-version: 1.20

main: ovh.mythmc.social.bukkit.SocialBukkitPlugin
softdepend: [ PlaceholderAPI ]

commands:
  social:
    permission: social.user
  pm:
    permission: social.command.pm
    aliases:
      - message
      - msg
      - whisper
      - w
      - tell
  reaction:
    permission: social.command.reaction
    aliases:
      - emote
      - e


permissions:
  social.user:
    default: true
  social.admin:
    default: op
    children:
      - social.command.*
      - social.filter.bypass
  social.command.*:
    default: op
    children:
      - social.command.channel
      - social.command.nickname
      - social.command.reaction
      - social.command.reload
      - social.command.socialspy
  social.command.channel:
    default: false
  social.command.nickname:
    default: false
  social.command.pm:
    default: true
  social.command.reaction:
    default: true
  social.command.reload:
    default: false
  social.command.socialspy:
    default: false
  social.filter.bypass:
    default: false