name: social
authors: [myth-MC, U8092]
version: '${project.version}'
api-version: 1.19

main: ovh.mythmc.social.bukkit.SocialPlatformBukkitPlugin
softdepend: [ PlaceholderAPI, DiscordSRV, gestalt ]

libraries:
  - net.kyori:adventure-api:4.18.0
  - net.kyori:adventure-platform-bukkit:4.3.4
  - net.kyori:adventure-text-minimessage:4.18.0
  - net.kyori:adventure-text-serializer-plain:4.18.0
  - net.kyori:adventure-text-serializer-gson:4.18.0
  - org.incendo:cloud-core:2.0.0
  - org.incendo:cloud-minecraft-extras:2.0.0-beta.10
  - org.incendo:cloud-paper:2.0.0-beta.10

permissions:
  social.use.nickname.others:
    description: Allows users to change other player's nicknames
    default: op
  social.filter.bypass:
    description: Allows users to bypass filter settings
    default: op
  social.mute.excempt:
    description: Allows users to bypass mute status
    default: op
  social.mentions:
    description: Allows users to mention other users
    default: true
  social.text-formatting:
    description: Allows users to format text
    default: true
  social.delete-messages.self:
    description: Allows users to delete their own messages
    default: op
  social.delete-messages.others:
    description: Allows users to delete other users' messages
    default: op