/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    implementation(project(":social-api"))
    implementation(project(":social-api-bukkit"))
    implementation(project(":social-common"))
    implementation(project(":social-bukkit"))
    compileOnly(libs.org.incendo.cloud.paper)
    compileOnly(libs.io.papermc.paper.paper.api)
}

plugins.withType<JavaPlugin> {
        the<JavaPluginExtension>().apply {
            sourceCompatibility = JavaVersion.VERSION_21
            targetCompatibility = JavaVersion.VERSION_21
        }
    }


tasks {
    processResources {
        val replacements = mapOf(
            "version" to version.toString()
        )
        inputs.properties(replacements)
        filesMatching("paper-plugin.yml") {
            expand(replacements)
        }
    }
}

description = "social-paper"
