/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("com.gradleup.shadow") version "9.0.0-beta10"
}

dependencies {
    implementation(project(path = ":social-bukkit", configuration = "shadow"))
    compileOnly(libs.org.incendo.cloud.paper)
    compileOnly(libs.io.papermc.paper.paper.api)
}

tasks.shadowJar {
    minimize()
}

description = "social-paper"
