/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":social-api"))
    compileOnly(libs.org.spigotmc.spigot.api)
}

description = "social-api-bukkit"
