/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("com.gradleup.shadow")
}

dependencies {
    api("ovh.mythmc:gestalt-loader:0.3.2")
    compileOnly("org.projectlombok:lombok:1.18.36")
    annotationProcessor("org.projectlombok:lombok:1.18.36")
    compileOnly("org.jetbrains:annotations:24.1.0")
    compileOnly("net.kyori:adventure-api:4.18.0")
    compileOnly("net.kyori:adventure-text-minimessage:4.18.0")
    compileOnly("net.kyori:adventure-text-serializer-plain:4.18.0")
    compileOnly("net.kyori:adventure-text-serializer-gson:4.18.0")
    compileOnly("ovh.mythmc:gestalt-api:0.3.2")
    compileOnly("ovh.mythmc:callbacks-lib:0.1.2")
    annotationProcessor("ovh.mythmc:callbacks-lib:0.1.2")
}

afterEvaluate {

    if (project.name == "social-api" ||
        project.name == "social-api-bukkit" ||
        project.name == "social-common") {

        extensions.configure<PublishingExtension>("publishing") {

            publications {
                create<MavenPublication>("maven") {
                    from(components["java"])
                }
            }

            repositories {
                maven {
                    val releasesRepoUrl = uri("https://repo.mythmc.ovh/releases/")
                    val snapshotsRepoUrl = uri("https://repo.mythmc.ovh/snapshots")

                    url = if (project.version.toString().contains("db") ||
                              project.version.toString().contains("rc"))
                        snapshotsRepoUrl
                    else
                        releasesRepoUrl

                    credentials {
                        username = findProperty("mythMcUser") as String?
                        password = findProperty("mythMcPassword") as String?
                    }
                }
            }
        }
    }
}

tasks.shadowJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    minimize()
    for (relocation in Relocations.relocations) {
        relocate(relocation.key, relocation.value)
    }
}