/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("com.gradleup.shadow")
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://repo.codemc.io/repository/maven-releases/")
    }

    maven {
        url = uri("https://repo.mythmc.ovh/releases/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    }

    maven {
        url = uri("https://nexus.scarsz.me/content/groups/public/")
    }

    maven {
        url = uri("https://repo.papermc.io/repository/maven-snapshots/")
    }
}

dependencies {
    api("ovh.mythmc:gestalt-loader:0.2.2")
    compileOnly("org.projectlombok:lombok:1.18.36")
    annotationProcessor("org.projectlombok:lombok:1.18.36")
    compileOnly("org.jetbrains:annotations:24.1.0")
    compileOnly("net.kyori:adventure-api:4.18.0")
    compileOnly("net.kyori:adventure-text-minimessage:4.18.0")
    compileOnly("net.kyori:adventure-text-serializer-plain:4.18.0")
    compileOnly("net.kyori:adventure-text-serializer-gson:4.18.0")
    compileOnly("ovh.mythmc:gestalt-api:0.2.2")
    compileOnly("ovh.mythmc:callbacks-lib:0.1.2")
    annotationProcessor("ovh.mythmc:callbacks-lib:0.1.2")
}

group = "ovh.mythmc"
version = providers.gradleProperty("version").get()
java.sourceCompatibility = JavaVersion.VERSION_17

afterEvaluate {

    if (project.name == "social-api" ||
        project.name == "social-api-bukkit" ||
        project.name == "social-common") {

        extensions.configure<PublishingExtension>("publishing") {

            publications {
                create<MavenPublication>("maven") {
                    from(components["java"])
                }
            }

            repositories {
                maven {
                    val releasesRepoUrl = uri("https://repo.mythmc.ovh/releases/")
                    val snapshotsRepoUrl = uri("https://repo.mythmc.ovh/snapshots")

                    url = if (project.version.toString().contains("db") ||
                              project.version.toString().contains("rc"))
                        snapshotsRepoUrl
                    else
                        releasesRepoUrl

                    credentials {
                        username = findProperty("mythMcUser") as String?
                        password = findProperty("mythMcPassword") as String?
                    }
                }
            }
        }
    }
}

tasks.withType<Javadoc>().configureEach {
    (options as StandardJavadocDocletOptions).apply {

        // Java standard library
        links("https://docs.oracle.com/en/java/javase/17/docs/api/")

        // Adventure API
        links("https://jd.advntr.dev/api/4.26.1/")

        // JetBrains annotations
        links("https://javadoc.io/doc/org.jetbrains/annotations/26.1.0/")
    }
}

tasks.shadowJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    minimize()
    for (relocation in Relocations.relocations) {
        relocate(relocation.key, relocation.value)
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}