/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("com.gradleup.shadow") version "9.0.0-beta10"
}

dependencies {
    api(project(path = ":social-api", configuration = "shadow"))
    compileOnly(libs.org.incendo.cloud.core) // Platform implementations decide whether to shade it
    compileOnly(libs.org.incendo.cloud.minecraft.extras) // ^
}

description = "social-common"
