/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    compileOnly(project(path = ":social-api")) // API should be available at runtime
    compileOnly(libs.org.incendo.cloud.core) // Platform implementations decide whether to shade it
    compileOnly(libs.org.incendo.cloud.minecraft.extras) // ^
}

description = "social-common"
