/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.de.exlll.configlib.yaml)
    api(libs.com.j256.ormlite.ormlite.core)
    api(libs.com.j256.ormlite.ormlite.jdbc)
}

description = "social-api"
